name: CI/CD data preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRAIN_DATA_URL: "coffeebeans_raw/train"
  TEST_DATA_URL: "coffeebeans_raw/test"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $TRAIN_DATA_URL
          echo $TEST_DATA_URL
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow numpy pillow
      
      # Debug: Check directory structure
      - name: Check directory
        run: |
          ls -la
          pwd
          ls -la coffeebeans_raw/ || echo "coffeebeans_raw not found"
          
      # Run as a mlflow project
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Faqihuddin-Al-Ghiffary.py
          ls -la preprocessing/
          ls -la preprocessing/coffeebeans_preprocessing/ || echo "Folder not found"
      
      # Upload hasil preprocessing sebagai artifact
      - name: Upload preprocessing results
        uses: actions/upload-artifact@v4
        with:
          name: preprocessing-results
          path: preprocessing/coffeebeans_preprocessing/

      - name: Commit preprocessing results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/coffeebeans_preprocessing/
          git commit -m "Add preprocessing results" || echo "No changes"
          git push

